[package]
name = "ansi-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
clap = { version = "4.0", features = ["derive"] }
assert_cmd = "2.0.16"

[[bin]]
name = "ansi-gen"
path = "src/main.rs"
